### ISSUE TITLE
This is an extremley bad mod.

### ISSUE THREAD

**Issue by HausemasterIssue** [chris2rich/ChunkLimit#1]
I can think of a thousand different ways to bypass this and build dupe stashes. Use droppers, hoppers, dispensers, use dispensers to place down shulkers etc. Not only that but it greatly can impede on normal gameplay due to the fact that yes many players build storage systems or have some moderate sized storage that would look familiar to a dupe stash.

**Comment by chris2rich** [comment]
this was made almost a year ago
